name: v_chat_sdk_sample
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.5
  shared_preferences: ^2.0.17
  flutter_facebook_auth: ^5.0.7
  http: ^0.13.5
  smooth_page_indicator: ^1.0.0+2
  the_apple_sign_in: ^1.1.1
  flutter_bloc: ^8.1.1
  bottom_navy_bar: ^6.0.0
  url_launcher: ^6.1.8
  firebase_messaging: ^14.2.1
  custom_navigation_bar: ^0.8.2
  introduction_screen: ^3.1.4
  flex_color_scheme: ^6.1.2
  get: 4.6.5
  flutter: 
    sdk: flutter
  v_chat_sdk_core: ^0.4.3+2
  v_chat_web_rtc: ^0.0.1
  v_chat_utils: ^0.4.3
  v_chat_receive_share: ^0.2.0
  v_chat_message_page: ^0.4.3+1
  v_chat_firebase_fcm: ^0.4.3
  v_chat_room_page: ^0.4.3+2
  animated_login: ^1.6.1
  shimmer: ^2.0.0
  fluttertoast: ^8.1.2
  path: ^1.8.2
  encrypt: ^5.0.1
  http_parser: ^4.0.2
  flutter_localizations:
    sdk: flutter
  v_chat_one_signal: ^0.4.3
  callkeep: ^0.3.3
dev_dependencies:
  flutter_test: 
    sdk: flutter

flutter_icons: 
  android: ic_launcher
  image_path: assets/images/logo.png
  ios: true
  remove_alpha_ios: true

flutter: 
  assets: 
    - assets/images/
  uses-material-design: true
flutter_intl:
  enabled: false
