name: v_chat_firebase_fcm
description: v chat fcm implementations
version: 0.7.0
homepage: https://hatemragab.github.io/VChatSdk-Documentation/
issue_tracker: https://github.com/hatemragab/v_chat_sdk/issues
repository: https://github.com/hatemragab/v_chat_sdk/tree/master/push_providers/v_chat_one_signal

environment:
  sdk: '>=2.17.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  v_chat_utils: ^0.7.0
  v_chat_sdk_core: ^0.7.0
  firebase_core: ^2.7.0
  firebase_messaging: ^14.2.5
  eraser: ^2.0.1
  flutter_app_badger: ^1.5.0
  http: ^0.13.5

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  lints: ^2.0.1

flutter:

platforms:
  android:
  ios:
  web:
  windows:
  macos:
