name: v_chat_web_rtc
description: v chat web rtc call implementations
version: 0.6.1
homepage: https://hatemragab.github.io/VChatSdk-Documentation/
issue_tracker: https://github.com/hatemragab/v_chat_sdk/issues
repository: https://github.com/hatemragab/v_chat_sdk/tree/v2/v_ui_packages/v_chat_web_rtc


environment:
  sdk: '>=2.17.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  v_chat_sdk_core: ^0.6.1
  v_chat_utils: ^0.6.1
  flutter_webrtc: ^0.9.23
  pip_view: ^0.9.7
  retry: ^3.1.0
  sdp_transform: ^0.3.2
  stop_watch_timer: ^2.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

platforms:
  android:
  ios:
  web:
  windows:
  macos:
