name: voice_example
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.17.0 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  v_chat_utils: ^0.0.3
  flutter_cache_manager: ^3.3.0
  sizer: ^2.0.15
  v_chat_voice_player:
    path: ../
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

